### PR TITLE
agent: send full data to agent

### LINKED ISSUE #580: proxy doesn't send the full container structure to the agent
some field like `noNewPrivileges` and `capabilities` are not send to the agent, hence the agent does not apply them in the containers

I debugged the issue and I found cc-proxy sends this data to the agent
```
Jan 23 09:10:00 X cc-proxy[2771]: time="2018-01-23T09:10:00.338574448-06:00" level=info msg="hyper(cmd=\\\"newcontainer\\\", data=\\\"{\\\\\\\"id\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974\\\\\\\",\\\\\\\"rootfs\\\\\\\":\\\\\\\"rootfs\\\\\\\",\\\\\\\"image\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974\\\\\\\",\\\\\\\"fsmap\\\\\\\":[{\\\\\\\"source\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974-86142d4cf8d1ada5-resolv.conf\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/etc/resolv.conf\\\\\\\",\\\\\\\"readOnly\\\\\\\":false,\\\\\\\"dockerVolume\\\\\\\":false,\\\\\\\"absolutePath\\\\\\\":false},{\\\\\\\"source\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974-60fbcf1ad8f9ad0d-hostname\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/etc/hostname\\\\\\\",\\\\\\\"readOnly\\\\\\\":false,\\\\\\\"dockerVolume\\\\\\\":false,\\\\\\\"absolutePath\\\\\\\":false},{\\\\\\\"source\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974-565b36978f1580a2-hosts\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/etc/hosts\\\\\\\",\\\\\\\"readOnly\\\\\\\":false,\\\\\\\"dockerVolume\\\\\\\":false,\\\\\\\"absolutePath\\\\\\\":false}],\\\\\\\"process\\\\\\\":{\\\\\\\"user\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"group\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"terminal\\\\\\\":true,\\\\\\\"args\\\\\\\":[\\\\\\\"bash\\\\\\\"],\\\\\\\"envs\\\\\\\":[{\\\\\\\"env\\\\\\\":\\\\\\\"PATH\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\\\\\"},{\\\\\\\"env\\\\\\\":\\\\\\\"HOSTNAME\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"833a2954a7b9\\\\\\\"},{\\\\\\\"env\\\\\\\":\\\\\\\"TERM\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"xterm\\\\\\\"}],\\\\\\\"workdir\\\\\\\":\\\\\\\"/\\\\\\\",\\\\\\\"noNewPrivileges\\\\\\\":false,\\\\\\\"capabilities\\\\\\\":{\\\\\\\"bounding\\\\\\\":[\\\\\\\"CAP_CHOWN\\\\\\\",\\\\\\\"CAP_DAC_OVERRIDE\\\\\\\",\\\\\\\"CAP_FSETID\\\\\\\",\\\\\\\"CAP_FOWNER\\\\\\\",\\\\\\\"CAP_MKNOD\\\\\\\",\\\\\\\"CAP_NET_RAW\\\\\\\",\\\\\\\"CAP_SETGID\\\\\\\",\\\\\\\"CAP_SETUID\\\\\\\",\\\\\\\"CAP_SETFCAP\\\\\\\",\\\\\\\"CAP_SETPCAP\\\\\\\",\\\\\\\"CAP_NET_BIND_SERVICE\\\\\\\",\\\\\\\"CAP_SYS_CHROOT\\\\\\\",\\\\\\\"CAP_KILL\\\\\\\",\\\\\\\"CAP_AUDIT_WRITE\\\\\\\"],\\\\\\\"effective\\\\\\\":[\\\\\\\"CAP_CHOWN\\\\\\\",\\\\\\\"CAP_DAC_OVERRIDE\\\\\\\",\\\\\\\"CAP_FSETID\\\\\\\",\\\\\\\"CAP_FOWNER\\\\\\\",\\\\\\\"CAP_MKNOD\\\\\\\",\\\\\\\"CAP_NET_RAW\\\\\\\",\\\\\\\"CAP_SETGID\\\\\\\",\\\\\\\"CAP_SETUID\\\\\\\",\\\\\\\"CAP_SETFCAP\\\\\\\",\\\\\\\"CAP_SETPCAP\\\\\\\",\\\\\\\"CAP_NET_BIND_SERVICE\\\\\\\",\\\\\\\"CAP_SYS_CHROOT\\\\\\\",\\\\\\\"CAP_KILL\\\\\\\",\\\\\\\"CAP_AUDIT_WRITE\\\\\\\"],\\\\\\\"inheritable\\\\\\\":[\\\\\\\"CAP_CHOWN\\\\\\\",\\\\\\\"CAP_DAC_OVERRIDE\\\\\\\",\\\\\\\"CAP_FSETID\\\\\\\",\\\\\\\"CAP_FOWNER\\\\\\\",\\\\\\\"CAP_MKNOD\\\\\\\",\\\\\\\"CAP_NET_RAW\\\\\\\",\\\\\\\"CAP_SETGID\\\\\\\",\\\\\\\"CAP_SETUID\\\\\\\",\\\\\\\"CAP_SETFCAP\\\\\\\",\\\\\\\"CAP_SETPCAP\\\\\\\",\\\\\\\"CAP_NET_BIND_SERVICE\\\\\\\",\\\\\\\"CAP_SYS_CHROOT\\\\\\\",\\\\\\\"CAP_KILL\\\\\\\",\\\\\\\"CAP_AUDIT_WRITE\\\\\\\"],\\\\\\\"permitted\\\\\\\":[\\\\\\\"CAP_CHOWN\\\\\\\",\\\\\\\"CAP_DAC_OVERRIDE\\\\\\\",\\\\\\\"CAP_FSETID\\\\\\\",\\\\\\\"CAP_FOWNER\\\\\\\",\\\\\\\"CAP_MKNOD\\\\\\\",\\\\\\\"CAP_NET_RAW\\\\\\\",\\\\\\\"CAP_SETGID\\\\\\\",\\\\\\\"CAP_SETUID\\\\\\\",\\\\\\\"CAP_SETFCAP\\\\\\\",\\\\\\\"CAP_SETPCAP\\\\\\\",\\\\\\\"CAP_NET_BIND_SERVICE\\\\\\\",\\\\\\\"CAP_SYS_CHROOT\\\\\\\",\\\\\\\"CAP_KILL\\\\\\\",\\\\\\\"CAP_AUDIT_WRITE\\\\\\\"],\\\\\\\"ambient\\\\\\\":null}},\\\\\\\"restartPolicy\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"initialize\\\\\\\":false,\\\\\\\"systemMountsInfo\\\\\\\":{\\\\\\\"bindMountDev\\\\\\\":false,\\\\\\\"devShmSize\\\\\\\":0},\\\\\\\"constraints\\\\\\\":{\\\\\\\"CPUQuota\\\\\\\":40000,\\\\\\\"CPUPeriod\\\\\\\":10000}}\\\")" client=4 name=cc-proxy pid=2771 source=proxy
```

but the agent does not receive the full data

```
Jan 23 09:10:00 X cc-proxy[2771]: time="2018-01-23T09:10:00.34009406-06:00" level=debug msg="{\\\"level\\\":\\\"info\\\",\\\"msg\\\":\\\"##### data: {\\\\\\\"id\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974\\\\\\\",\\\\\\\"rootfs\\\\\\\":\\\\\\\"rootfs\\\\\\\",\\\\\\\"image\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974\\\\\\\",\\\\\\\"fsmap\\\\\\\":[{\\\\\\\"source\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974-86142d4cf8d1ada5-resolv.conf\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/etc/resolv.conf\\\\\\\",\\\\\\\"readOnly\\\\\\\":false,\\\\\\\"dockerVolume\\\\\\\":false,\\\\\\\"absolutePath\\\\\\\":false},{\\\\\\\"source\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974-60fbcf1ad8f9ad0d-hostname\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/etc/hostname\\\\\\\",\\\\\\\"readOnly\\\\\\\":false,\\\\\\\"dockerVolume\\\\\\\":false,\\\\\\\"absolutePath\\\\\\\":false},{\\\\\\\"source\\\\\\\":\\\\\\\"833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974-565b36978f1580a2-hosts\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/etc/hosts\\\\\\\",\\\\\\\"readOnly\\\\\\\":false,\\\\\\\"dockerVolume\\\\\\\":false,\\\\\\\"absolutePath\\\\\\\":false}],\\\\\\\"process\\\\\\\":{\\\\\\\"user\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"group\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"terminal\\\\\\\":true,\\\\\\\"stdio\\\\\\\":3,\\\\\\\"args\\\\\\\":[\\\\\\\"bash\\\\\\\"],\\\\\\\"envs\\\\\\\":[{\\\\\\\"env\\\\\\\":\\\\\\\"PATH\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\\\\\"},{\\\\\\\"env\\\\\\\":\\\\\\\"HOSTNAME\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"833a2954a7b9\\\\\\\"},{\\\\\\\"env\\\\\\\":\\\\\\\"TERM\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"xterm\\\\\\\"}],\\\\\\\"workdir\\\\\\\":\\\\\\\"/\\\\\\\"},\\\\\\\"restartPolicy\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"initialize\\\\\\\":false,\\\\\\\"systemMountsInfo\\\\\\\":{\\\\\\\"bindMountDev\\\\\\\":false,\\\\\\\"devShmSize\\\\\\\":0}}\\\",\\\"name\\\":\\\"cc-agent\\\",\\\"pid\\\":160,\\\"time\\\":\\\"2018-01-23T15:10:00.329547945Z\\\"}" name=cc-proxy pid=2771 source=qemu vm=833a2954a7b9ec8deb9476bcd2a4224184060dd1dd06dcfd241271887308e974
```

### PR DESCRIPTION
**Pull request by devimc**
don't use pointers to structures in the data that is sent
to the agent

Depends-on: github.com/clearcontainers/proxy#208

fixes #580

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@devimc the pointers should be marshalled to json fields correctly. Can you describe what issue you are seeing?

**Comment by devimc** [comment]
@amshinde done, I described it in the issue

**Comment by devimc** [comment]
just vendoring virtcontainer in the proxy won't fix the issue, I tested it

**Comment by amshinde** [comment]
@devimc Vendoring should solve the issue unless I am missing something, else we would have seen this issue for all other fields.

**Comment by jodh-intel** [comment]
It would be good if we could have a test to ensure the behaviour is as we want, but...

lgtm

**Comment by sameo** [comment]
@devimc Let's wait and see if @amshinde proxy vendoring fixes that issue.

**Comment by devimc** [comment]
clearcontainers/proxy#196 was merged  and seems like this pr is not needed

**Pull request closed without merging**
