### PR TITLE
Vendor OCI runtime specification

### PR DESCRIPTION
**Pull request by sboeuf**
This PR initializes the vendoring of virtcontainers repo with "dep" tool. Particularly, it vendors the OCI runtime spec because we cannot rely on a version more recent than the one used by Docker.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Wow - you win the :medal_sports: for most file changes on a PR so far! :smile:

lgtm

**Comment by dlespiau** [comment]
@sboeuf This branch needed to be rebased and I clicked the "update branch" button, which merges master into your PR... oops. Mind rebasing and updating this PR?

**Comment by sboeuf** [comment]
rebased !

**Comment by dlespiau** [comment]
This means every user of virtcontainers needs to use go tool dep. Maybe that's fine, but maybe that's a bit soon?

Not opposed to merging this, but might need reverting if there's a user out there we don't know about and uses another vendoring tool.

**Pull request merged**
