### PR TITLE
pod: Add function to get a specific container

### PR DESCRIPTION
**Pull request by devimc**
GetContainer returns the container named by containerID (param)

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
@devimc the change looks ok to me, but could you also rename `GetContainers()` to `GetAllContainers()` to make the API less confusing ?

**Comment by devimc** [comment]
@sameo yes

**Comment by devimc** [comment]
@sameo  done

**Comment by sameo** [comment]
LGTM

**Pull request merged**
