### PR TITLE
Add bindmount checks

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by sameo** [comment]
@jodh Could you please rebase and see if travis picks it up this time ?

**Comment by sameo** [comment]
LGTM

**Comment by Jodh** [comment]
Hi,
I think you are sending these requests to the wrong Jodh.

Regards

Jodh Singh


On Mar 13, 2017 6:01 AM, "Samuel Ortiz" <notifications@github.com> wrote:

LGTM

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/containers/virtcontainers/pull/151#issuecomment-286063062>,
or mute the thread

**Comment by sameo** [comment]
@jodh Apologies...

**Comment by sboeuf** [comment]
@jodh-intel could you re-submit this ? Travis is stuck...

**Comment by jodh-intel** [comment]
@sboeuf - done.

**Pull request merged**
