### PR TITLE
vendor: Updates

### PR DESCRIPTION
**Pull request by sameo**
We need the ciao qemu locking changes:

f12f43d Knobs: Modify the behaviour of the Mlock knob

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
I assume this is the change mentioned at  https://github.com/clearcontainers/runtime/pull/550#issuecomment-330315119.

Could you add in the git shortlog showing the changes for ciao?

**Comment by sameo** [comment]
> Could you add in the git shortlog showing the changes for ciao?

@jodh-intel Done.

**Comment by jodh-intel** [comment]
Thanks.

lgtm

**Comment by sboeuf** [comment]
LGTM

**Pull request merged**
