### PR TITLE
Add support for NoNewPrivileges in oci spec

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by sboeuf** [comment]
@amshinde also please fix unit tests.

**Comment by jodh-intel** [comment]
lgtm

Can you raise an issue on https://github.com/clearcontainers/tests to capture the requirement for a new set of tests for this option when it lands in the runtime?

**Comment by sameo** [comment]
LGTM

I suppose this depends on an agent change as well?

**Comment by amshinde** [comment]
@sameo Yes, here is the agent change : https://github.com/clearcontainers/agent/pull/186

**Comment by amshinde** [comment]
@jodh-intel I have submitted an issue to follow up on adding a new test for this:
https://github.com/clearcontainers/tests/issues/811

**Comment by amshinde** [comment]
@sboeuf  Can you merge if this looks good?

**Comment by sboeuf** [comment]
LGTM

**Pull request merged**
