### PR TITLE
qemu: disable modern in SCSI constroller

### LINKED ISSUE #663: disable modern in SCSI constroller
disable modern to allow virtual containers run in virtual machines, like azure VMs

### PR DESCRIPTION
**Pull request by devimc**
Disable modern to prevent qemu from relying on fast MMIO.
This change is needed to avoid boot issues when using virtio-scsi in a
nested virtual machine scenario.

fixes #663

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@devimc dont you need to revendor govmm here?

**Comment by devimc** [comment]
@sboeuf @amshinde done

**Comment by sboeuf** [comment]
LGTM

**Comment by devimc** [comment]
@egernst  done

**Comment by egernst** [comment]
Looks good -- happy to see it merged after the CI finishes up.  Thanks @devimc

**Pull request merged**
