### PR TITLE
Ignore route with ipv6 gateway

### PR DESCRIPTION
**Pull request by amshinde**
We ignore routes that have an ipv6 destination, since we do not have support for ipv6 currently. We should do the same for default route that has an ipv6 gateway address.

### CODE REVIEW

**Comment by amshinde** [comment]
@mcastelino @egernst PTAL

**Comment by mcastelino** [comment]
@chavafg can we enable IPv6 in our docker CI https://docs.docker.com/config/daemon/ipv6/

This will help catch issues easily. We should ignore IPv6 settings till we support them.

**Comment by amshinde** [comment]
Changes to two different agent implementations, makes sense to have them in a separate commit. We can revert one once we add ipv6 support.

**Comment by sboeuf** [comment]
@amshinde I don't mind having one or two commits here, but please could you add a subsystem for each of your commit messages, identifying which component is modified:
`kata_agent: ipv6: ...`
`hyperstart_agent: ipv6: ...`

Or simply squash them. Up to you !

**Comment by amshinde** [comment]
@sboeuf I have modified the commit message.

**Comment by sboeuf** [comment]
@amshinde LGTM

**Comment by amshinde** [comment]
@sboeuf I see the fedora CI failing this time, even though I just changed the commit message.
http://cc-jenkins-ci.westus2.cloudapp.azure.com/job/virtcontainers-fedora-26-PR/519/console
```
--- FAIL: TestRunPodHyperstartAgentSuccessful (0.04s)
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] listening on /tmp/cc-proxy-test162776106/cc-proxy-test.sock
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Client connected
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Register VM
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Error serving client : EOF
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Client closed connection
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Client connected
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Attach VM
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Hyper command
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Error serving client : EOF
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Client closed connection
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Client connected
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Attach VM
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Error serving client : EOF
21:48:14 	cc_proxy_mock.go:90: [CCProxyMock] Client closed connection
21:48:14 	api_test.go:778: Could not bind mount /tmp/virtcontainers-tmp-636974255/bundle to /run/hyper/shared/pods/7f49d00d-1995-4156-8c79-5f5ab24ce138/1/rootfs: no such file or directory
```

I am going to rerun to see if I get the same error, but maybe a potential bug/race somewhere else in our code.

**Comment by sboeuf** [comment]
@amshinde some race conditions in our unit tests... I have re-triggered a build already.

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
