### PR TITLE
logging: Use structured logging

### LINKED ISSUE #398: Switch to structured logging
Review all log messages and rework them to use structured logging for parity with other system elements.

### PR DESCRIPTION
**Pull request by jodh-intel**
Switch to structured logging for parity with other system components.

Fixes #398.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This is getting hit by the github issue (status.github.com) - the newest commit *should* be showing as ccd0c750485df5c2683883b6826883722174441e.

**Comment by jodh-intel** [comment]
\o/ - github is alive once again.

**Comment by jodh-intel** [comment]
@sameo, @amshinde, @sboeuf - could you take a look please?

**Comment by sameo** [comment]
LGTM

**Pull request merged**
