### PR TITLE
virtcontainers: Switch the repository to read-only mode

### PR DESCRIPTION
**Pull request by sboeuf**
This commit moves the original README to README-original.md in order
to keep it, and modify the new README to indicate the new location of
virtcontainers in github.com/kata-containers/runtime.

This also introduces a new file error_package_moved.go which prevents
the package from building properly. This is done on purpose, to avoid
confusion for the users of this package, forcing them to update their
dependency to the right repository.

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@jodh-intel @egernst @grahamwhaley @sameo PTAL
The CI for this PR won't pass since it introduces a new file which is not going to build properly. We should merge it when we get LGTM from at least 3 or 4 people from the team here.

**Review by grahamwhaley — APPROVED** [review]
lgtm

I wonder if you can get git/github to realise the README file was renamed - it does not show like that on the PR/diff.
but.... not a problem, just a thought.

**Comment by jodh-intel** [comment]
Thanks @sboeuf!

lgtm

[Approved with PullApprove](https://pullapprove.com/containers/virtcontainers/pull-request/676/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=containers/virtcontainers) [Approved with PullApprove](https://pullapprove.com/containers/virtcontainers/pull-request/676/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=containers/virtcontainers)

**Comment by jodh-intel** [comment]
Of course, this will have to be force-merged given `error_package_moved.go`.

**Pull request merged**
