### PR TITLE
vendor: Move the ciao vendoring to ciao-project

### PR DESCRIPTION
**Pull request by sameo**
The ciao project moved to a new github organization:
github.com/ciao-project. Although they continue syncing the old 01.org
repo, we should switch sooner than later.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
cc @mcastelino

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Comment by mcastelino** [comment]
@sameo should we just move qemu to be under clearcontainers repo or a top level repo in ciao. We should just do it once for all. 
/cc @markdryan

**Comment by sameo** [comment]
@mcastelino If the ciao folks are ok with it, we definitely can, yes.

**Comment by markdryan** [comment]
@sameo, @mcastelino Moving qemu out of ciao is on my todo list but it's going to take a little bit of time.  So probably best to merge this change for now.

**Comment by sboeuf** [comment]
@sameo @markdryan sorry I didn't follow up on this one. What do you suggest ? Should I rebase this PR so that we can get it merged ??

**Comment by markdryan** [comment]
rebasing sounds like a good idea.  I just merged a patch from @amshinde into github.com/ciao-project/ciao/qemu this morning.

**Comment by sboeuf** [comment]
@markdryan I thought it was my PR.... @sameo can you rebase and re-push so that we have latest ciao version vendored in virtcontainers.

**Comment by devimc** [comment]
also please include a short log

**Comment by sameo** [comment]
rebased.
@devimc There are no vendoring changes, just a rename. So the shortlog is essentially empty.

**Pull request merged**
