### PR TITLE
Networking: Add support for multiqueue tap and multiqueue vhost

### LINKED ISSUE #247: Networking - Enable Multi-Queue virtio-net
_From @mcastelino on August 24, 2016 16:10_

Multi-queue virtio-net provides an approach that scales the network performance as the number of vCPUs increases, by allowing them to transfer packets through more than one virtqueue pair at a time.

_Copied from original issue: 01org/cc-oci-runtime#162_

### PR DESCRIPTION
**Pull request by mcastelino**
Networking: Add support for multiqueue tap

Add support for multiqueue tap for the bridge mode.
This improves the multi-q performance of bridge mode.
However macvtap mode is still faster.

Fixes #247

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
@mcastelino Could you please rebase that one?

**Comment by sameo** [comment]
@mcastelino https://github.com/clearcontainers/runtime/pull/856 is merged. Once rebased, the new CI builds _should_ pass now...

**Comment by sboeuf** [comment]
LGTM

**Comment by mcastelino** [comment]
@sameo @sboeuf rebased to latest qemu and netlink.
@egernst added your commit too so that you do not need to revendor for vhost-user networking.

**Comment by sboeuf** [comment]
@mcastelino great thx ! Let's wait for the CI, and I'll merge this right after !

**Comment by mcastelino** [comment]
@sboeuf the CI fails due to runtime vendoring issues

```
23:19:39 go build -i -o cc-runtime .
23:19:43 # github.com/clearcontainers/runtime/vendor/github.com/containers/virtcontainers
23:19:43 vendor/github.com/containers/virtcontainers/qemu.go:357: unknown field 'VhostFDs' in struct literal of type qemu.NetDevice
```

This is a bug in our CI as it does not pick up the updated QEMU in the runtime. This is our typical chicken and egg vendoring situation.

@chavafg is there a way around this?

**Comment by sboeuf** [comment]
We have a real problem here, we cannot make this PR passing with the way our CI handle nested vendoring for the runtime. Let's force merge this PR since it looks good to everybody. And we will expect the full CI to run properly on the PR from the runtime revendoring virtcontainers.

**Comment by sameo** [comment]
@sboeuf Could you please file a CI issue for this?

**Comment by sboeuf** [comment]
@sameo oh yes I forgot to do that! I'll do it right away!

**Pull request merged**
