### PR TITLE
Test for addDrive in container.go

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by amshinde** [comment]
This needs to be merged after #325

**Comment by jodh-intel** [comment]
Yay for new tests! \o/ :smile:

But I don't see why this cannot be part of #325 itself? That new code and these tests for it in my mind are a "logical unit". If that makes #325 a big change, so be it.

In my mind it sense to land the feature + the code at the same time. Otherwise, there is still a window when you have untested code in `master`.

**Comment by amshinde** [comment]
Semaphore failing here because OBS package got kernel cannot be downloaded. Need to rerun until OBS is up or https://github.com/clearcontainers/tests/pull/514 is merged.

**Comment by amshinde** [comment]
@jodh-intel @sameo Can you take a look at this?

**Comment by sameo** [comment]
LGTM

**Pull request merged**
