### PR TITLE
Revert "Merge pull request #584 from amshinde/switch-to-scsi"

### PR DESCRIPTION
**Pull request by sboeuf**
This reverts commit 494b46c5bfa0c305fa3e2ad9d15ca12af2c148a5, reversing
changes made to e475a8fcc486f83b1719166aa8e5a936c14f72e5.

THIS IS A TEST PR.

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @sboeuf - I see that this is a test PR, but please can you explain why this revert is needed? In fact, could you raise an issue with full details?

**Comment by sboeuf** [comment]
@jodh-intel yes that was a test PR, let me talk with @amshinde before we take a decision about this.

**Comment by amshinde** [comment]
@jodh-intel We are seeing  some random failures with hotplug test for virtio-scsi: 
https://github.com/clearcontainers/runtime/pull/1039
I'll be taking a look at this today to see what the exact issue is.

**Comment by amshinde** [comment]
The issue was due to an old version of agent being used in our CI. We can close this now. I have rerun CI for this VC PR: https://github.com/containers/virtcontainers/pull/649
Once that passes, we can close this PR.

**Comment by sboeuf** [comment]
@amshinde sounds good to me :)

**Comment by sboeuf** [comment]
#649 passed as expected, let's close this then !

**Pull request closed without merging**
