### PR TITLE
virtcontainers: Global re-organisation of the proxy/shim code

### LINKED ISSUE #518: Rework of the proxy interface
With both `cc-proxy`, `kata-proxy` and the `no-proxy` cases, I have been thinking that our current `proxy` interface does not meet all the needs for those different cases...
First I think we don't need to return a URL when calling into `connect()` or a list of URL when calling into `register()`, only one URL should be returned by `start()` now that we agreed on the model one proxy per VM. This opinion is based on the fact that a proxy is at a pod/VM level and I don't expect several URLs to be provided to the shim, the same way this shim will connect to only one socket on the VM in case we don't go through a proxy.
Then I think that most of the interface is fine, except `sendCmd()`. I have been turning the problem upside down, but no way to make all the cases work with this. We should agree on what should be a proxy in order to know what to expect from it. I think a proxy has to be accessed the same way we would access the VM directly, that is through a socket. This is already the case for all our different cases, but the problem is about the way the data are processed and are expected to be received by this proxy or directly by the VM. The most generic way I can think of is by sending an array of bytes through the socket opened through the `connect()`. This would suggest that `connect()` would actually return a handler to this socket connection. We should get rid of the `sendCmd()` because it assumes the agent to know about the kind of proxy that is going to be used, while a pure array of bytes sent through the provided socket would be processed either by the proxy or directly by the agent, transparently for virtcontainers. Indeed, we should use this generic socket handler from the agent implementation in order to call into some specific functions (specific to the agent protocol) but always requiring a socket to communicate to.
All what I am suggesting here would be pretty straight forward to implement for both `kata-proxy` and `no-proxy` since they follow this model of receiving the same data, the encapsulation being done by the proxy itself if needed.
But this would require some extra work for our current `cc-proxy` and `cc_proxy.go` implementation since the encapsulation is done by the client itself.
One first step to avoid too much changes would be to consider using the `sendCmd()` the way it is right now, only for the `cc-proxy` case, while we would not use it for other new implementations. Instead, we would only use the subset `start()`, `register()`, `unregister()`, `connect()`, `disconnect()`.
This is the first time we're really testing the flexibility of virtcontainers interfaces, and I would like to make sure we move in the right direction by refining them in case we see a need for that. And I think this is the case here.

@sameo @jodh-intel WDYT ?

### PR DESCRIPTION
**Pull request by sboeuf**
This PR mainly reworks the proxy interface of virtcontainers, pushes shim and proxy down the stack, that is hidden behind the agent.

Fixes #518

### CODE REVIEW

**Comment by sboeuf** [comment]
@egernst yes that's the plan !

**Comment by sboeuf** [comment]
@jodh-intel @sameo PR is ready, tested and CI is passing, please review it. I am gonna re-upload an updated version for the commit message later.

**Comment by jodh-intel** [comment]
@sboeuf - Wowzers - a biggie. I'll take a look at this tomorrow morning as didn't get round to this today I'm afraid.

**Comment by jodh-intel** [comment]
@sboeuf - I like it! A simpler proxy interface *and* a simpler agent interface :)

lgtm

**Comment by sameo** [comment]
LGTM

**Pull request merged**
