### PR TITLE
Remove redundant "if" checks

### PR DESCRIPTION
**Pull request by WeiZhang555**
Some "if" checks are redundant, we can remove them and return error
directly instead.

Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
This is detected by a latest golint tools, I can see that you have enabled gometalinter tools in you CI, I guess the reason that gometalinter didn't detected this is that it's using a old golint tool.

As the issue is real, I think it's better to fix this, or we still need to fix this someday when we updated gometalinter. :smile:

**Comment by sboeuf** [comment]
LGTM

**Comment by sboeuf** [comment]
@WeiZhang555 thanks for the PR, I agree it's good to clean those asap!

**Comment by WeiZhang555** [comment]
@sboeuf 🤝 👍

**Pull request merged**
